import type { MediaItem, Creator, Comment } from './types';

export const creators: Creator[] = [
  {
    id: 'c1', name: '自然之眼', avatar: '/images/avatar1.jpg',
    bio: '风光摄影师 | 用镜头记录山川湖海的壮阔与宁静，追逐光影中的诗意瞬间。',
    followers: 12840, following: 326, posts: 87, totalLikes: 284700, level: 5,
    isVerified: true, followed: false, joinedAt: '2023-03',
    location: '云南·大理', website: 'https://natureeye.photo',
    tags: ['风光', '自然', '旅行'],
  },
  {
    id: 'c2', name: 'UrbanLens', avatar: '/images/avatar2.jpg',
    bio: '城市纪实摄影 | 捕捉都市中被忽略的角落与故事，让每条街巷都有温度。',
    followers: 8920, following: 215, posts: 134, totalLikes: 152300, level: 4,
    isVerified: true, followed: false, joinedAt: '2023-06',
    location: '上海', tags: ['城市', '街拍', '纪实'],
  },
  {
    id: 'c3', name: '肖像工坊', avatar: '/images/avatar3.jpg',
    bio: '人像摄影师 | 光影是最好的画笔，每个人都值得一张有灵魂的肖像。',
    followers: 23100, following: 189, posts: 56, totalLikes: 320100, level: 5,
    isVerified: true, followed: false, joinedAt: '2022-11',
    location: '北京', tags: ['人像', '艺术', '光影'],
  },
  {
    id: 'c4', name: '海洋之声', avatar: '/images/avatar4.jpg',
    bio: '水下/海洋摄影师 | 潜入深蓝，记录海洋的呼吸与律动。',
    followers: 45200, following: 98, posts: 203, totalLikes: 567200, level: 6,
    isVerified: true, followed: false, joinedAt: '2022-05',
    location: '三亚', website: 'https://oceansound.cn',
    tags: ['海洋', '水下', '自然'],
  },
  {
    id: 'c5', name: 'FoodieShot', avatar: '/images/avatar1.jpg',
    bio: '美食摄影 | 让每一道菜都成为艺术品，用镜头唤醒味蕾。',
    followers: 6780, following: 412, posts: 245, totalLikes: 98400, level: 3,
    isVerified: false, followed: false, joinedAt: '2024-01',
    location: '成都', tags: ['美食', '生活', '摄影'],
  },
  {
    id: 'c6', name: 'TrailBlazer', avatar: '/images/avatar3.jpg',
    bio: '户外探险摄影师 | 走过千山万水，镜头是我的旅伴。',
    followers: 31500, following: 156, posts: 178, totalLikes: 412000, level: 5,
    isVerified: true, followed: false, joinedAt: '2022-08',
    location: '西藏·拉萨', tags: ['户外', '登山', '旅行'],
  },
  {
    id: 'c7', name: '猫咪控', avatar: '/images/avatar4.jpg',
    bio: '宠物摄影师 | 专注记录毛孩子们的可爱日常，治愈你的每一天。',
    followers: 52300, following: 890, posts: 567, totalLikes: 893400, level: 6,
    isVerified: true, followed: false, joinedAt: '2022-01',
    location: '杭州', tags: ['宠物', '猫咪', '日常'],
  },
  {
    id: 'c8', name: 'NorthernSky', avatar: '/images/avatar2.jpg',
    bio: '天文摄影爱好者 | 仰望星空，追逐极光，记录宇宙的浪漫。',
    followers: 67800, following: 45, posts: 89, totalLikes: 1234000, level: 6,
    isVerified: true, followed: false, joinedAt: '2021-09',
    location: '冰岛', tags: ['天文', '极光', '星空'],
  },
];

function makeComments(count: number): Comment[] {
  const pool = [
    { author: '小明', avatar: '/images/avatar1.jpg', text: '太美了！构图和色彩都很棒 📸' },
    { author: 'Sarah', avatar: '/images/avatar2.jpg', text: 'Absolutely stunning! What camera did you use?' },
    { author: '摄影爱好者', avatar: '/images/avatar3.jpg', text: '构图很棒，色彩也很好，学习了！' },
    { author: 'Alex', avatar: '/images/avatar4.jpg', text: 'Where was this taken? I need to visit! 😍' },
    { author: '旅行者', avatar: '/images/avatar1.jpg', text: '好想去这个地方！请问是哪里拍的？' },
    { author: 'Mike', avatar: '/images/avatar3.jpg', text: 'Great composition and lighting, truly professional work.' },
    { author: '小红', avatar: '/images/avatar2.jpg', text: '分享到朋友圈了！太喜欢这种风格了' },
    { author: 'Emma', avatar: '/images/avatar4.jpg', text: 'This is breathtaking! ✨ Added to my collection.' },
    { author: '大卫', avatar: '/images/avatar1.jpg', text: '用什么相机拍的？参数能分享一下吗？' },
    { author: 'Luna', avatar: '/images/avatar2.jpg', text: '加入我的灵感板了，太有意境了！' },
    { author: '光影猎人', avatar: '/images/avatar3.jpg', text: '后期处理得很自然，不过度不失真，赞！' },
    { author: '云游客', avatar: '/images/avatar4.jpg', text: '每次看你的作品都能感受到一种宁静的力量' },
  ];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const now = Date.now();
  return shuffled.slice(0, count).map((c, i) => ({
    id: `cmt-${Math.random().toString(36).slice(2, 9)}`,
    author: c.author,
    avatar: c.avatar,
    text: c.text,
    createdAt: now - (i + 1) * 3600000 * (Math.random() * 24 + 1),
    likes: Math.floor(Math.random() * 80),
    liked: false,
  }));
}

const now = Date.now();
const hour = 3600000;
const day = hour * 24;

export const mediaItems: MediaItem[] = [
  {
    id: 'm1', type: 'photo', src: '/images/photo1.jpg',
    title: '湖光山色·晨曦', description: '清晨五点半出发，等待了两个小时，终于等到了这束光。湖面如镜，群山倒映，仿佛时间在这一刻静止。这是我在大理洱海边最难忘的一次拍摄经历。',
    author: creators[0], likes: 2847, views: 18920, comments: makeComments(6),
    tags: ['风光', '湖泊', '山脉', '日出', '自然'], category: '风光',
    createdAt: now - 2 * hour, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7R V', lens: 'FE 16-35mm f/2.8 GM II', aperture: 'f/11', shutter: '1/125s', iso: 'ISO 100', focalLength: '24mm' },
    location: '云南·大理·洱海', copyright: 'CC BY-NC 4.0', width: 1920, height: 1280,
  },
  {
    id: 'm2', type: 'photo', src: '/images/photo2.jpg',
    title: '夜色街巷', description: '上海老城区的一条小巷，霓虹灯光与老建筑交织出独特的都市韵味。雨后的地面倒映着五彩的光，像是另一个世界的入口。',
    author: creators[1], likes: 1523, views: 9840, comments: makeComments(4),
    tags: ['城市', '夜景', '街拍', '上海'], category: '城市',
    createdAt: now - 5 * hour, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Fujifilm X-T5', lens: 'XF 23mm f/1.4 R LM WR', aperture: 'f/1.4', shutter: '1/60s', iso: 'ISO 3200', focalLength: '23mm' },
    location: '上海·老城厢', copyright: 'All Rights Reserved', width: 1920, height: 1280,
  },
  {
    id: 'm3', type: 'photo', src: '/images/photo3.jpg',
    title: '光影人像·复古', description: '一组复古风格的人像作品，利用自然光和百叶窗营造出电影般的光影效果。模特的表情与光线完美配合，每一帧都像是一幅油画。',
    author: creators[2], likes: 3201, views: 22100, comments: makeComments(7),
    tags: ['人像', '艺术', '光影', '复古', '胶片'], category: '人像',
    createdAt: now - 8 * hour, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Canon EOS R5', lens: 'RF 85mm f/1.2L USM', aperture: 'f/1.8', shutter: '1/200s', iso: 'ISO 400', focalLength: '85mm' },
    location: '北京·798艺术区', copyright: 'CC BY-NC-ND 4.0', width: 1280, height: 1920,
  },
  {
    id: 'm4', type: 'photo', src: '/images/photo4.jpg',
    title: '味蕾盛宴', description: '米其林三星餐厅的招牌海鲜拼盘，主厨精心摆盘，每一个细节都是艺术。食物摄影的魅力在于让观者隔着屏幕也能感受到美味。',
    author: creators[4], likes: 987, views: 6230, comments: makeComments(3),
    tags: ['美食', '摄影', '餐厅', '海鲜'], category: '美食',
    createdAt: now - 12 * hour, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7 IV', lens: 'FE 90mm f/2.8 Macro', aperture: 'f/4', shutter: '1/80s', iso: 'ISO 800', focalLength: '90mm' },
    location: '成都·太古里', copyright: 'All Rights Reserved', width: 1400, height: 1400,
  },
  {
    id: 'm5', type: 'video', src: '/videos/video1.mp4', thumbnail: '/images/photo5.jpg',
    title: '日落海浪·延时', description: '历时3小时的延时摄影，记录了从午后到日落的完整过程。海浪拍打沙滩的节奏与天空色彩的变化交织成一首视觉交响曲。使用滑轨拍摄，后期调色参考了胶片风格。',
    author: creators[3], likes: 5672, views: 42300, comments: makeComments(8),
    tags: ['海洋', '日落', '延时', '视频', '海浪'], category: '视频',
    createdAt: now - 1 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7S III', lens: 'FE 24-70mm f/2.8 GM II', aperture: 'f/8', shutter: '1/500s', iso: 'ISO 200', focalLength: '35mm' },
    location: '三亚·亚龙湾', copyright: 'CC BY-NC 4.0', width: 1920, height: 1080,
  },
  {
    id: 'm6', type: 'photo', src: '/images/photo6.jpg',
    title: '山巅行者', description: '攀登海拔5200米的雪山途中，回望来时的路，云海翻涌在脚下。那一刻，所有的疲惫都化为了感动。这张照片是队友在我不知情时拍下的。',
    author: creators[5], likes: 4123, views: 28900, comments: makeComments(5),
    tags: ['登山', '冒险', '旅行', '雪山', '户外'], category: '旅行',
    createdAt: now - 1.5 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Nikon Z8', lens: 'NIKKOR Z 24-120mm f/4 S', aperture: 'f/8', shutter: '1/1000s', iso: 'ISO 200', focalLength: '50mm' },
    location: '西藏·念青唐古拉', copyright: 'CC BY 4.0', width: 1920, height: 1280,
  },
  {
    id: 'm7', type: 'photo', src: '/images/photo7.jpg',
    title: '喵星人日记', description: '家里的小橘猫，最喜欢趴在窗台上晒太阳。阳光洒在它毛茸茸的身上，暖融融的，看着就让人心情好。记录生活中的小确幸。',
    author: creators[6], likes: 8934, views: 67200, comments: makeComments(9),
    tags: ['宠物', '猫咪', '可爱', '日常', '治愈'], category: '宠物',
    createdAt: now - 2 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A6700', lens: 'Sigma 56mm f/1.4', aperture: 'f/2', shutter: '1/320s', iso: 'ISO 400', focalLength: '56mm' },
    location: '杭州·家中', copyright: 'CC BY-NC 4.0', width: 1400, height: 1400,
  },
  {
    id: 'm8', type: 'photo', src: '/images/photo8.jpg',
    title: '建筑之美·曲线', description: '现代建筑的曲线美学，钢与玻璃在阳光下呈现出令人惊叹的几何韵律。建筑摄影的魅力在于发现日常中被忽略的美。',
    author: creators[1], likes: 1876, views: 11400, comments: makeComments(4),
    tags: ['建筑', '设计', '现代', '几何', '城市'], category: '建筑',
    createdAt: now - 2.5 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Canon EOS R6 II', lens: 'RF 14-35mm f/4L IS USM', aperture: 'f/8', shutter: '1/250s', iso: 'ISO 100', focalLength: '14mm' },
    location: '深圳·南山', copyright: 'All Rights Reserved', width: 1280, height: 1920,
  },
  {
    id: 'm9', type: 'photo', src: '/images/photo9.jpg',
    title: '春日花语·郁金香', description: '春天的郁金香花海，色彩斑斓如同大自然的调色板。微风拂过，花浪翻涌，空气中弥漫着淡淡的花香。这是属于春天最美的礼物。',
    author: creators[0], likes: 2345, views: 15600, comments: makeComments(5),
    tags: ['花卉', '春天', '色彩', '自然', '郁金香'], category: '自然',
    createdAt: now - 3 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7R V', lens: 'FE 70-200mm f/2.8 GM II', aperture: 'f/4', shutter: '1/500s', iso: 'ISO 200', focalLength: '135mm' },
    location: '荷兰·库肯霍夫', copyright: 'CC BY-NC 4.0', width: 1920, height: 1280,
  },
  {
    id: 'm10', type: 'photo', src: '/images/photo10.jpg',
    title: '拉花艺术', description: '一杯好咖啡，从拉花开始。这是我在成都一家独立咖啡馆拍摄的，咖啡师的手法行云流水，每一杯都是独一无二的艺术品。',
    author: creators[4], likes: 1234, views: 8900, comments: makeComments(3),
    tags: ['咖啡', '艺术', '生活', '拉花'], category: '生活',
    createdAt: now - 3.5 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Fujifilm X100V', aperture: 'f/2', shutter: '1/125s', iso: 'ISO 1600', focalLength: '23mm' },
    location: '成都·宽窄巷子', copyright: 'CC BY 4.0', width: 1400, height: 1400,
  },
  {
    id: 'm11', type: 'video', src: '/videos/video2.mp4', thumbnail: '/images/photo11.jpg',
    title: '极光之舞·冰岛', description: '在冰岛守候了整整一周，终于在最后一晚等到了这场壮观的极光秀。绿色、紫色的光带在夜空中舞动，仿佛宇宙在向我们展示它的魔法。全程手持拍摄，后期仅做了基础调色。',
    author: creators[7], likes: 12453, views: 89200, comments: makeComments(10),
    tags: ['极光', '夜空', '冰岛', '视频', '天文'], category: '视频',
    createdAt: now - 4 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7S III', lens: 'FE 14mm f/1.8 GM', aperture: 'f/1.8', shutter: '4s', iso: 'ISO 6400', focalLength: '14mm' },
    location: '冰岛·维克', copyright: 'CC BY-NC-ND 4.0', width: 1920, height: 1080,
  },
  {
    id: 'm12', type: 'photo', src: '/images/photo12.jpg',
    title: '街头画布', description: '城市的墙壁是街头艺术家的画布，每一幅涂鸦都承载着创作者的态度与表达。这面墙位于柏林东区画廊附近，色彩鲜艳而充满力量。',
    author: creators[1], likes: 3456, views: 21300, comments: makeComments(5),
    tags: ['街头', '涂鸦', '艺术', '色彩', '柏林'], category: '艺术',
    createdAt: now - 5 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Ricoh GR IIIx', aperture: 'f/5.6', shutter: '1/250s', iso: 'ISO 200', focalLength: '40mm' },
    location: '柏林·东区画廊', copyright: 'CC BY 4.0', width: 1920, height: 1280,
  },
  {
    id: 'm13', type: 'photo', src: '/images/photo13.jpg',
    title: '丛林猎手', description: '在非洲大草原上蹲守了三天，终于捕捉到这只花豹进食的珍贵瞬间。野生动物摄影需要极大的耐心和运气，但每一次成功都让人热血沸腾。',
    author: creators[5], likes: 6789, views: 45600, comments: makeComments(7),
    tags: ['野生动物', '花豹', '非洲', '自然', '纪实'], category: '自然',
    createdAt: now - 5.5 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Nikon Z9', lens: 'NIKKOR Z 400mm f/2.8 TC VR S', aperture: 'f/4', shutter: '1/2000s', iso: 'ISO 800', focalLength: '560mm' },
    location: '肯尼亚·马赛马拉', copyright: 'All Rights Reserved', width: 1920, height: 1280,
  },
  {
    id: 'm14', type: 'photo', src: '/images/photo14.jpg',
    title: '鸟瞰海岸线', description: '无人机航拍的海岸线，碧蓝的海水与金色的沙滩形成鲜明对比。从高空俯瞰，大自然的鬼斧神工令人叹为观止。',
    author: creators[3], likes: 5432, views: 38700, comments: makeComments(6),
    tags: ['航拍', '海岸', '无人机', '蓝色', '自然'], category: '风光',
    createdAt: now - 6 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'DJI Mavic 3 Pro', aperture: 'f/2.8', shutter: '1/1000s', iso: 'ISO 100', focalLength: '24mm' },
    location: '澳大利亚·大堡礁', copyright: 'CC BY-NC 4.0', width: 1920, height: 1280,
  },
  {
    id: 'm15', type: 'photo', src: '/images/photo15.jpg',
    title: '银河拱桥', description: '在海拔4000米的高原上，远离光污染，银河如一道璀璨的拱桥横跨天际。这是一张由12张照片拼接而成的全景图，前后期共耗时8小时。',
    author: creators[7], likes: 15678, views: 112000, comments: makeComments(10),
    tags: ['银河', '星空', '天文', '全景', '高原'], category: '天文',
    createdAt: now - 7 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Nikon Z8', lens: 'NIKKOR Z 14-24mm f/2.8 S', aperture: 'f/2.8', shutter: '20s', iso: 'ISO 4000', focalLength: '14mm' },
    location: '青海·茶卡盐湖', copyright: 'CC BY-NC-ND 4.0', width: 1920, height: 1080,
  },
  {
    id: 'm16', type: 'photo', src: '/images/photo16.jpg',
    title: '樱花古寺', description: '京都的春天，古寺与樱花的完美邂逅。粉白的花瓣随风飘落，落在青石板路上，美得让人不忍离去。日本的侘寂美学在这里体现得淋漓尽致。',
    author: creators[0], likes: 7890, views: 56300, comments: makeComments(8),
    tags: ['樱花', '日本', '古寺', '旅行', '春天'], category: '旅行',
    createdAt: now - 8 * day, liked: false, saved: false, isOriginal: true,
    exif: { camera: 'Sony A7C II', lens: 'FE 35mm f/1.4 GM', aperture: 'f/2.8', shutter: '1/500s', iso: 'ISO 200', focalLength: '35mm' },
    location: '日本·京都·清水寺', copyright: 'CC BY-NC 4.0', width: 1920, height: 1280,
  },
];

export const categories = ['全部', '风光', '城市', '人像', '美食', '旅行', '自然', '宠物', '建筑', '艺术', '生活', '天文', '视频'];

export const trendingTags = [
  { name: '风光', count: 12840 },
  { name: '人像', count: 9820 },
  { name: '街拍', count: 8430 },
  { name: '日落', count: 7210 },
  { name: '猫咪', count: 6890 },
  { name: '旅行', count: 6540 },
  { name: '星空', count: 5230 },
  { name: '美食', count: 4890 },
  { name: '建筑', count: 4120 },
  { name: '极光', count: 3670 },
];
